# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ldGMcVY7YuXUagbgGiPkoTIIqJH77yFZ
"""

import urllib.request
import urllib.request
import gzip
import shutil
import pandas as pd
import numpy as np
import re
url = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE19nnn/GSE19804/matrix/GSE19804_series_matrix.txt.gz"
urllib.request.urlretrieve(url, "GSE19804_series_matrix.txt.gz")

with gzip.open("GSE19804_series_matrix.txt.gz", "rb") as f_in:
    with open("GSE19804_series_matrix.txt", "wb") as f_out:
        shutil.copyfileobj(f_in, f_out)

print("Downloaded and unzipped.")
geo_ids = []
titles = []

with open("GSE19804_series_matrix.txt", "r", encoding="latin1") as f:
    for line in f:
        if line.startswith("!Sample_geo_accession"):
            geo_ids = [x.strip().strip('"') for x in line.strip().split("\t")[1:]]
        if line.startswith("!Sample_title"):
            titles = [x.strip().strip('"') for x in line.strip().split("\t")[1:]]
        if line.startswith("!series_matrix_table_begin"):
            break

print("Number of samples found:", len(geo_ids))
print("First 5 GEO IDs:", geo_ids[:5])
print("First 5 titles:", titles[:5])
def parse_condition(title):
    if "Cancer" in title or title.strip().endswith("T"):
        return "Tumor"
    elif "Normal" in title or title.strip().endswith("N"):
        return "Normal"
    else:
        return "Unknown"

def parse_pair_id(title):
    match = re.search(r'(\d+)[TN]?\s*$', title.strip())
    return match.group(1) if match else None

metadata = pd.DataFrame({
    "sample_id": geo_ids,
    "title": titles
})
metadata["condition"] = metadata["title"].apply(parse_condition)
metadata["pair_id"] = metadata["title"].apply(parse_pair_id)

print(metadata["condition"].value_counts())
print("\nAny 'Unknown' labels? ->", (metadata["condition"] == "Unknown").sum())
metadata.head(10)
pair_check = metadata.groupby("pair_id")["condition"].apply(lambda x: sorted(x.tolist()))
unpaired = pair_check[pair_check.apply(lambda x: x != ["Normal", "Tumor"])]
print("Number of pair_ids total:", pair_check.shape[0])
print("Unpaired/mismatched pair_ids (should be empty):")
print(unpaired)
expr = pd.read_csv(
    "GSE19804_series_matrix.txt",
    sep="\t",
    comment="!",
    index_col=0,
    skip_blank_lines=True
)
expr = expr.dropna(how="all")

print("Expression matrix shape (probes x samples):", expr.shape)
print("Value range: min =", expr.values.min(), " max =", expr.values.max())
expr.head()
print("Columns match metadata sample_id order?", list(expr.columns) == list(metadata["sample_id"]))
print("Any sample in expr not in metadata?", set(expr.columns) - set(metadata["sample_id"]))
print("Any sample in metadata not in expr?", set(metadata["sample_id"]) - set(expr.columns))
metadata.to_csv("GSE19804_metadata.csv", index=False)
expr.to_csv("GSE19804_expression_matrix.csv")
print("Saved metadata and expression matrix.")
from google.colab import files

files.download("GSE19804_metadata.csv")
files.download("GSE19804_expression_matrix.csv")

import pandas as pd
import numpy as np
from scipy import stats
from statsmodels.stats.multitest import multipletests
expr = pd.read_csv("GSE19804_expression_matrix.csv", index_col=0)
metadata = pd.read_csv("GSE19804_metadata.csv")

print("Expression matrix:", expr.shape)
print("Metadata rows:", metadata.shape[0])
meta_tumor = metadata[metadata["condition"] == "Tumor"].sort_values("pair_id")
meta_normal = metadata[metadata["condition"] == "Normal"].sort_values("pair_id")
assert list(meta_tumor["pair_id"]) == list(meta_normal["pair_id"]), \
    "Pair IDs do not align between Tumor and Normal — STOP, fix before continuing"

tumor_ids = meta_tumor["sample_id"].tolist()
normal_ids = meta_normal["sample_id"].tolist()

tumor_df = expr[tumor_ids]
normal_df = expr[normal_ids]

print("Tumor samples:", tumor_df.shape)
print("Normal samples:", normal_df.shape)
print("Pair alignment confirmed for", len(tumor_ids), "patients")
log2fc = tumor_df.mean(axis=1) - normal_df.mean(axis=1)

t_stats, p_values = stats.ttest_rel(tumor_df.values, normal_df.values, axis=1)

deg_table = pd.DataFrame({
    "probe_id": expr.index,
    "log2FC": log2fc.values,
    "t_statistic": t_stats,
    "p_value": p_values
})

print("DEG table shape:", deg_table.shape)
deg_table.head()
reject, fdr_values, _, _ = multipletests(deg_table["p_value"], method="fdr_bh")
deg_table["FDR"] = fdr_values

# Check for any NaN p-values (can happen if a probe has zero variance)
n_nan = deg_table["p_value"].isna().sum()
print("Probes with NaN p-value (zero variance, will be excluded from significant set):", n_nan)
def get_direction(row):
    if row["FDR"] < 0.05 and row["log2FC"] > 1:
        return "Up"
    elif row["FDR"] < 0.05 and row["log2FC"] < -1:
        return "Down"
    else:
        return "Not Significant"

deg_table["direction"] = deg_table.apply(get_direction, axis=1)

print(deg_table["direction"].value_counts())
full_deg_table = deg_table.sort_values("FDR")
significant_deg_table = full_deg_table[full_deg_table["direction"] != "Not Significant"].copy()

print("Total probes tested:", full_deg_table.shape[0])
print("Significant DEGs (FDR<0.05, |log2FC|>1):", significant_deg_table.shape[0])
print("  Upregulated:", (significant_deg_table["direction"] == "Up").sum())
print("  Downregulated:", (significant_deg_table["direction"] == "Down").sum())

significant_deg_table.head(10)
full_deg_table.to_csv("GSE19804_full_DEG_table.csv", index=False)
significant_deg_table.to_csv("GSE19804_significant_DEG_table.csv", index=False)

from google.colab import files
files.download("GSE19804_full_DEG_table.csv")
files.download("GSE19804_significant_DEG_table.csv")

print("Saved and downloaded both DEG tables.")

!pip install GEOparse --quiet
import GEOparse
gpl = GEOparse.get_GEO(geo="GPL570", destdir="./geo_cache")
print(gpl.table.shape)
gpl.table.head()
import pandas as pd
probe_to_gene = gpl.table[["ID", "Gene Symbol"]].copy()
probe_to_gene.columns = ["probe_id", "gene_symbol"]
probe_to_gene["gene_symbol"] = probe_to_gene["gene_symbol"].astype(str).apply(
    lambda x: x.split("///")[0].strip() if x not in ["nan", ""] else None
)

n_unmapped = probe_to_gene["gene_symbol"].isna().sum()
print("Total probes:", probe_to_gene.shape[0])
print("Probes with no gene symbol mapping:", n_unmapped)

probe_to_gene.head()
full_deg_table = pd.read_csv("GSE19804_full_DEG_table.csv")
significant_deg_table = pd.read_csv("GSE19804_significant_DEG_table.csv")

full_deg_table = full_deg_table.merge(probe_to_gene, on="probe_id", how="left")
significant_deg_table = significant_deg_table.merge(probe_to_gene, on="probe_id", how="left")

n_sig_unmapped = significant_deg_table["gene_symbol"].isna().sum()
print("Significant DEGs with no gene symbol:", n_sig_unmapped, "out of", significant_deg_table.shape[0])

significant_deg_table.sort_values("FDR").head(10)
full_deg_table.to_csv("GSE19804_full_DEG_table_annotated.csv", index=False)
significant_deg_table_dedup.to_csv("GSE19804_significant_DEG_table_genes.csv", index=False)

from google.colab import files
files.download("GSE19804_full_DEG_table_annotated.csv")
files.download("GSE19804_significant_DEG_table_genes.csv")

print("Saved and downloaded gene-annotated DEG tables.")
significant_deg_table_dedup = (
    significant_deg_table
    .dropna(subset=["gene_symbol"])
    .sort_values("FDR")
    .drop_duplicates(subset="gene_symbol", keep="first")
)

print("Significant, gene-mapped DEGs before dedup:",
      significant_deg_table.dropna(subset=["gene_symbol"]).shape[0])
print("Significant DEGs after collapsing duplicate-probe genes:",
      significant_deg_table_dedup.shape[0])

significant_deg_table_dedup.sort_values("FDR").head(10)
full_deg_table.to_csv("GSE19804_full_DEG_table_annotated.csv", index=False)
significant_deg_table_dedup.to_csv("GSE19804_significant_DEG_table_genes.csv", index=False)

from google.colab import files
files.download("GSE19804_full_DEG_table_annotated.csv")
files.download("GSE19804_significant_DEG_table_genes.csv")

print("Saved and downloaded gene-annotated DEG tables.")
print(significant_deg_table_dedup["direction"].value_counts())

significant_deg_table_dedup = (
    significant_deg_table
    .dropna(subset=["gene_symbol"])
    .sort_values("FDR")
    .drop_duplicates(subset="gene_symbol", keep="first")
)

print("Significant, gene-mapped DEGs before dedup:",
      significant_deg_table.dropna(subset=["gene_symbol"]).shape[0])
print("Significant DEGs after collapsing duplicate-probe genes:",
      significant_deg_table_dedup.shape[0])

significant_deg_table_dedup.sort_values("FDR").head(10)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
expr = pd.read_csv("GSE19804_expression_matrix.csv", index_col=0)
metadata = pd.read_csv("GSE19804_metadata.csv")
full_deg_table = pd.read_csv("GSE19804_full_DEG_table_annotated.csv")
significant_deg_table_dedup = pd.read_csv("GSE19804_significant_DEG_table_genes.csv")

print("Loaded:", expr.shape, metadata.shape, full_deg_table.shape, significant_deg_table_dedup.shape)
plot_df = full_deg_table.dropna(subset=["FDR"]).copy()
plot_df["neg_log10_FDR"] = -np.log10(plot_df["FDR"].replace(0, 1e-300))

plot_df["category"] = "Not Significant"
plot_df.loc[(plot_df["FDR"] < 0.05) & (plot_df["log2FC"] > 1), "category"] = "Up"
plot_df.loc[(plot_df["FDR"] < 0.05) & (plot_df["log2FC"] < -1), "category"] = "Down"

plt.figure(figsize=(9, 7))
colors = {"Not Significant": "lightgrey", "Up": "#d62728", "Down": "#1f77b4"}
for cat, color in colors.items():
    subset = plot_df[plot_df["category"] == cat]
    plt.scatter(subset["log2FC"], subset["neg_log10_FDR"], s=5, c=color, label=cat, alpha=0.6)

plt.axvline(1, color="black", linestyle="--", linewidth=0.8)
plt.axvline(-1, color="black", linestyle="--", linewidth=0.8)
plt.axhline(-np.log10(0.05), color="black", linestyle="--", linewidth=0.8)
plt.xlabel("log2 Fold Change (Tumor vs Normal)")
plt.ylabel("-log10(FDR)")
plt.title("Volcano Plot: GSE19804 Tumor vs Normal (Non-smoking Female Lung Cancer)")
plt.legend(title="DEG status", markerscale=3)
plt.tight_layout()
plt.savefig("volcano_plot.png", dpi=300)
plt.show()
top50 = significant_deg_table_dedup.sort_values("FDR").head(50)
top50_probes = top50["probe_id"].tolist()
top50_labels = top50["gene_symbol"].tolist()

heatmap_data = expr.loc[top50_probes]
heatmap_data.index = top50_labels
ordered_samples = (
    metadata.sort_values(["condition", "pair_id"], ascending=[False, True])["sample_id"].tolist()
)
heatmap_data = heatmap_data[ordered_samples]
heatmap_z = heatmap_data.sub(heatmap_data.mean(axis=1), axis=0).div(heatmap_data.std(axis=1), axis=0)
condition_order = metadata.set_index("sample_id").loc[ordered_samples, "condition"]
col_colors = condition_order.map({"Tumor": "#d62728", "Normal": "#1f77b4"})

g = sns.clustermap(
    heatmap_z,
    col_cluster=False,
    row_cluster=True,
    col_colors=col_colors,
    cmap="vlag",
    figsize=(14, 12),
    xticklabels=False,
    yticklabels=True,
    cbar_kws={"label": "Z-score"}
)
g.fig.suptitle("Top 50 DEGs: Tumor (red bar) vs Normal (blue bar)", y=1.02)
g.savefig("heatmap_top50.png", dpi=300, bbox_inches="tight")
plt.show()
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
X = expr.T.values
X_scaled = StandardScaler().fit_transform(X)

pca = PCA(n_components=2)
pcs = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(pcs, columns=["PC1", "PC2"])
pca_df["sample_id"] = expr.columns
pca_df = pca_df.merge(metadata[["sample_id", "condition"]], on="sample_id")

explained_var = pca.explained_variance_ratio_ * 100

plt.figure(figsize=(8, 7))
for condition, color in zip(["Tumor", "Normal"], ["#d62728", "#1f77b4"]):
    subset = pca_df[pca_df["condition"] == condition]
    plt.scatter(subset["PC1"], subset["PC2"], c=color, label=condition, s=40, alpha=0.7, edgecolors="white")

plt.xlabel(f"PC1 ({explained_var[0]:.1f}% variance)")
plt.ylabel(f"PC2 ({explained_var[1]:.1f}% variance)")
plt.title("PCA: Tumor vs Normal Samples (GSE19804)")
plt.legend()
plt.tight_layout()
plt.savefig("pca_plot.png", dpi=300)
plt.show()
from google.colab import files
files.download("volcano_plot.png")
files.download("heatmap_top50.png")
files.download("pca_plot.png")
print("All three plots saved and downloaded.")
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
sig_probes = significant_deg_table_dedup["probe_id"].tolist()
expr_sig = expr.loc[sig_probes]

X_sig = expr_sig.T.values
X_sig_scaled = StandardScaler().fit_transform(X_sig)

pca_sig = PCA(n_components=2)
pcs_sig = pca_sig.fit_transform(X_sig_scaled)

pca_sig_df = pd.DataFrame(pcs_sig, columns=["PC1", "PC2"])
pca_sig_df["sample_id"] = expr_sig.columns
pca_sig_df = pca_sig_df.merge(metadata[["sample_id", "condition"]], on="sample_id")

explained_var_sig = pca_sig.explained_variance_ratio_ * 100

plt.figure(figsize=(8, 7))
for condition, color in zip(["Tumor", "Normal"], ["#d62728", "#1f77b4"]):
    subset = pca_sig_df[pca_sig_df["condition"] == condition]
    plt.scatter(subset["PC1"], subset["PC2"], c=color, label=condition, s=40, alpha=0.7, edgecolors="white")

plt.xlabel(f"PC1 ({explained_var_sig[0]:.1f}% variance)")
plt.ylabel(f"PC2 ({explained_var_sig[1]:.1f}% variance)")
plt.title("PCA Using Significant DEGs Only (n=1,401 genes)")
plt.legend()
plt.tight_layout()
plt.savefig("pca_plot_sig_genes_only.png", dpi=300)
plt.show()from google.colab import files
files.download("pca_plot_sig_genes_only.png")
print("Saved and downloaded.")
from google.colab import files
files.download("pca_plot_sig_genes_only.png")
print("Saved and downloaded.")
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
sig_probes = significant_deg_table_dedup["probe_id"].tolist()
expr_sig = expr.loc[sig_probes]

X_sig = expr_sig.T.values
X_sig_scaled = StandardScaler().fit_transform(X_sig)

pca_sig = PCA(n_components=2)
pcs_sig = pca_sig.fit_transform(X_sig_scaled)

pca_sig_df = pd.DataFrame(pcs_sig, columns=["PC1", "PC2"])
pca_sig_df["sample_id"] = expr_sig.columns
pca_sig_df = pca_sig_df.merge(metadata[["sample_id", "condition"]], on="sample_id")

explained_var_sig = pca_sig.explained_variance_ratio_ * 100

plt.figure(figsize=(8, 7))
for condition, color in zip(["Tumor", "Normal"], ["#d62728", "#1f77b4"]):
    subset = pca_sig_df[pca_sig_df["condition"] == condition]
    plt.scatter(subset["PC1"], subset["PC2"], c=color, label=condition, s=40, alpha=0.7, edgecolors="white")

plt.xlabel(f"PC1 ({explained_var_sig[0]:.1f}% variance)")
plt.ylabel(f"PC2 ({explained_var_sig[1]:.1f}% variance)")
plt.title("PCA Using Significant DEGs Only (n=1,401 genes)")
plt.legend()
plt.tight_layout()
plt.savefig("pca_plot_sig_genes_only.png", dpi=300)
plt.show()
from google.colab import files
files.download("pca_plot_sig_genes_only.png")
print("Saved and downloaded.")
g = sns.clustermap(
    heatmap_z,
    col_cluster=False,
    row_cluster=True,
    col_colors=col_colors,
    cmap="vlag",
    figsize=(22, 14),    # wider — more horizontal pixels per sample column
    xticklabels=False,
    yticklabels=True,
    dendrogram_ratio=(0.12, 0.05),
    cbar_kws={"label": "Z-score"}
)
g.fig.suptitle("Top 50 DEGs: Tumor (red bar) vs Normal (blue bar)", y=1.02)
g.savefig("heatmap_top50_v2.png", dpi=400, bbox_inches="tight")
plt.show()
from google.colab import files
files.download("heatmap_top50_v2.png")

!pip install gseapy --quiet
import gseapy as gp
import pandas as pd
significant_deg_table_dedup = pd.read_csv("GSE19804_significant_DEG_table_genes.csv")

up_genes = significant_deg_table_dedup[significant_deg_table_dedup["direction"] == "Up"]["gene_symbol"].dropna().tolist()
down_genes = significant_deg_table_dedup[significant_deg_table_dedup["direction"] == "Down"]["gene_symbol"].dropna().tolist()

print("Upregulated genes for enrichment:", len(up_genes))
print("Downregulated genes for enrichment:", len(down_genes))
go_bp_up = gp.enrichr(
    gene_list=up_genes,
    gene_sets=['GO_Biological_Process_2023'],
    organism='human',
    outdir=None
)
go_bp_up_results = go_bp_up.results.sort_values("Adjusted P-value")
print("GO BP (Up) — top 10 terms:")
go_bp_up_results[["Term", "Overlap", "P-value", "Adjusted P-value", "Genes"]].head(10)
go_bp_down = gp.enrichr(
    gene_list=down_genes,
    gene_sets=['GO_Biological_Process_2023'],
    organism='human',
    outdir=None
)
go_bp_down_results = go_bp_down.results.sort_values("Adjusted P-value")
print("GO BP (Down) — top 10 terms:")
go_bp_down_results[["Term", "Overlap", "P-value", "Adjusted P-value", "Genes"]].head(10)
kegg_up = gp.enrichr(
    gene_list=up_genes,
    gene_sets=['KEGG_2021_Human'],
    organism='human',
    outdir=None
)
kegg_up_results = kegg_up.results.sort_values("Adjusted P-value")
print("KEGG (Up) — top 10 pathways:")
kegg_up_results[["Term", "Overlap", "P-value", "Adjusted P-value", "Genes"]].head(10)
kegg_down = gp.enrichr(
    gene_list=down_genes,
    gene_sets=['KEGG_2021_Human'],
    organism='human',
    outdir=None
)
kegg_down_results = kegg_down.results.sort_values("Adjusted P-value")
print("KEGG (Down) — top 10 pathways:")
kegg_down_results[["Term", "Overlap", "P-value", "Adjusted P-value", "Genes"]].head(10)
go_bp_up_results.to_csv("GO_BP_upregulated.csv", index=False)
go_bp_down_results.to_csv("GO_BP_downregulated.csv", index=False)
kegg_up_results.to_csv("KEGG_upregulated.csv", index=False)
kegg_down_results.to_csv("KEGG_downregulated.csv", index=False)

print("All 4 enrichment result tables saved.")
from google.colab import files

files.download("GO_BP_upregulated.csv")
files.download("GO_BP_downregulated.csv")
files.download("KEGG_upregulated.csv")
files.download("KEGG_downregulated.csv")

print("Downloaded all 4 enrichment CSVs.")
print("Number of down genes:", len(down_genes))
print("Any duplicates?", len(down_genes) != len(set(down_genes)))
print("Any empty/None values?", any(g is None or str(g).strip() == "" for g in down_genes))
print("First 10 genes:", down_genes[:10])
print("Any non-string entries?", any(not isinstance(g, str) for g in down_genes))
# --- View top 10 results from each enrichment ---
print("=" * 60)
print("GO Biological Process — UPREGULATED genes")
print("=" * 60)
print(go_bp_up_results[["Term", "Overlap", "Adjusted P-value"]].head(10).to_string(index=False))

print("\n" + "=" * 60)
print("GO Biological Process — DOWNREGULATED genes")
print("=" * 60)
print(go_bp_down_results[["Term", "Overlap", "Adjusted P-value"]].head(10).to_string(index=False))

print("\n" + "=" * 60)
print("KEGG Pathways — UPREGULATED genes")
print("=" * 60)
print(kegg_up_results[["Term", "Overlap", "Adjusted P-value"]].head(10).to_string(index=False))

print("\n" + "=" * 60)
print("KEGG Pathways — DOWNREGULATED genes")
print("=" * 60)
print(kegg_down_results[["Term", "Overlap", "Adjusted P-value"]].head(10).to_string(index=False))
import time

print("Waiting 30 seconds before retrying KEGG (Down) to avoid rate limiting...")
time.sleep(30)

kegg_down = gp.enrichr(
    gene_list=down_genes,
    gene_sets=['KEGG_2021_Human'],
    organism='human',
    outdir=None
)
kegg_down_results = kegg_down.results.sort_values("Adjusted P-value")
print("KEGG (Down) — top 10 pathways:")
kegg_down_results[["Term", "Overlap", "P-value", "Adjusted P-value", "Genes"]].head(10)

!pip install networkx --quiet
import pandas as pd
import requests
import networkx as nx
significant_deg_table_dedup = pd.read_csv("GSE19804_significant_DEG_table_genes.csv")

from google.colab import drive
drive.mount('/content/drive')
import os

project_path = "/content/drive/MyDrive/Lung_Cancer_Transcriptomics_Project"
os.makedirs(project_path, exist_ok=True)
os.chdir(project_path)

print("Now working in:", os.getcwd())
print("Files currently in this folder:", os.listdir(project_path))
from google.colab import files
print("Select all your existing project CSVs/PNGs to upload into Drive permanently:")
uploaded = files.upload()

import shutil
for fname in uploaded.keys():
    shutil.move(fname, os.path.join(project_path, fname))

print("Moved into Drive:", os.listdir(project_path))
import os
print("Drive mounted?", os.path.exists("/content/drive/MyDrive"))
print("Current directory:", os.getcwd())

print("Upload remaining files: GSE19804_metadata.csv and GSE19804_expression_matrix.csv")
uploaded = files.upload()

for fname in uploaded.keys():
    shutil.move(fname, os.path.join(project_path, fname))

print("Moved into Drive:", uploaded.keys())
print("Full folder contents now:", os.listdir(project_path))

print("Upload batch 3: GO_BP_upregulated.csv, GO_BP_downregulated.csv, KEGG_upregulated.csv, KEGG_downregulated.csv (clean names only, no '(1)')")
uploaded = files.upload()

for fname in uploaded.keys():
    shutil.move(fname, os.path.join(project_path, fname))

print("Moved into Drive:", list(uploaded.keys()))

print("Upload batch 4: volcano_plot.png, heatmap_top50.png, pca_plot.png, pca_plot_sig_genes_only.png (clean names only)")
uploaded = files.upload()

for fname in uploaded.keys():
    shutil.move(fname, os.path.join(project_path, fname))

print("Moved into Drive:", list(uploaded.keys()))

print(sorted(os.listdir(project_path)))
print("Total files:", len(os.listdir(project_path)))

!pip install networkx --quiet

import pandas as pd
import requests
import networkx as nx
significant_deg_table_dedup = pd.read_csv("GSE19804_significant_DEG_table_genes.csv")
top_up = significant_deg_table_dedup[significant_deg_table_dedup["direction"] == "Up"].sort_values("FDR").head(75)
top_down = significant_deg_table_dedup[significant_deg_table_dedup["direction"] == "Down"].sort_values("FDR").head(75)
ppi_gene_list = pd.concat([top_up, top_down])["gene_symbol"].dropna().unique().tolist()
print("Genes going into PPI network:", len(ppi_gene_list))

string_api_url = "https://string-db.org/api/tsv/network"
params = {"identifiers": "%0d".join(ppi_gene_list),
    "species": 9606,
    "required_score": 700,}
response = requests.post(string_api_url, data=params)
print("Status code:", response.status_code)

import io
ppi_edges = pd.read_csv(io.StringIO(response.text), sep="\t")
print("Edges returned:", ppi_edges.shape)
ppi_edges.head()
G = nx.from_pandas_edgelist(
    ppi_edges,
    source="preferredName_A",
    target="preferredName_B",
    edge_attr="score" if "score" in ppi_edges.columns else None
)

print("Nodes (genes with at least one connection):", G.number_of_nodes())
print("Edges (interactions):", G.number_of_edges())
degree_centrality = nx.degree_centrality(G)
degree_count = dict(G.degree())

hub_df = pd.DataFrame({
    "gene": list(degree_count.keys()),
    "degree": list(degree_count.values()),
    "degree_centrality": [degree_centrality[g] for g in degree_count.keys()]
}).sort_values("degree", ascending=False)

print("Top 15 hub genes by degree:")
hub_df.head(15)
hub_df = hub_df.merge(
    significant_deg_table_dedup[["gene_symbol", "direction", "log2FC", "FDR"]],
    left_on="gene", right_on="gene_symbol", how="left"
).drop(columns="gene_symbol")

hub_df.head(15)
hub_df.to_csv("PPI_hub_genes.csv", index=False)

from google.colab import files
files.download("PPI_hub_genes.csv")
print("Saved and downloaded hub gene table.")
print(hub_df.head(15).to_string(index=False))

check = significant_deg_table_dedup[significant_deg_table_dedup["gene_symbol"].isin(["PCLAF", "ERO1A"])]
print(check)
hub_df_clean = hub_df.dropna(subset=["direction"]).copy()
print("Hub genes after removing non-DEG network neighbors:", hub_df_clean.shape[0])
hub_df_clean.head(15)
hub_df_clean.to_csv("PPI_hub_genes_clean.csv", index=False)

from google.colab import files
files.download("PPI_hub_genes_clean.csv")
print("Saved cleaned hub gene table.")
import os
print("Current working directory:", os.getcwd())
print("Files in project folder:", sorted(os.listdir()))
import shutil
shutil.move("/content/PPI_hub_genes_clean.csv", "/content/drive/MyDrive/Lung_Cancer_Transcriptomics_Project/PPI_hub_genes.csv")
print("Moved to Drive.")
import os
print("Current directory:", os.getcwd())
print(sorted(os.listdir()))

import pandas as pd

significant_deg_table_dedup = pd.read_csv("GSE19804_significant_DEG_table_genes.csv")
hub_df_clean = pd.read_csv("PPI_hub_genes_clean.csv")
candidate_genes = ["CDH5", "COL1A1", "AGER", "PECAM1", "TEK", "COL3A1", "ROBO4", "COL10A1", "ZWINT"]

biomarker_table = significant_deg_table_dedup[
    significant_deg_table_dedup["gene_symbol"].isin(candidate_genes)
][["gene_symbol", "direction", "log2FC", "FDR"]].copy()
biomarker_table = biomarker_table.merge(
    hub_df_clean[["gene", "degree"]], left_on="gene_symbol", right_on="gene", how="left"
).drop(columns="gene")
pathway_map = {
    "CDH5":   ("Regulation of angiogenesis / vascular signaling", "Top PPI hub (degree 7); strongest vascular gene; matches GO angiogenesis enrichment", "Literature search recommended (Step 9)"),
    "COL1A1": ("ECM-receptor interaction / ECM organization", "2nd hub (degree 4); central to ECM gene cluster (COL3A1, COL10A1); matches KEGG ECM-receptor pathway", "Literature search recommended (Step 9)"),
    "AGER":   ("AGE-RAGE signaling pathway", "Strongest DEG by FDR; independently confirmed downregulated in lung cancer in prior studies", "External literature confirmed (see Step 3 discussion)"),
    "PECAM1": ("Cell adhesion / vascular signaling", "PPI hub (degree 3); endothelial adhesion gene, vascular theme", "Literature search recommended (Step 9)"),
    "TEK":    ("Angiogenesis (Tie2 receptor)", "PPI hub (degree 3); receptor tyrosine kinase central to vascular biology", "Literature search recommended (Step 9)"),
    "COL3A1": ("ECM organization", "Connected to COL1A1 hub; reinforces ECM remodeling theme", "Literature search recommended (Step 9)"),
    "ROBO4":  ("Vascular/angiogenesis signaling", "PPI hub; endothelial-specific guidance receptor", "Literature search recommended (Step 9)"),
    "COL10A1":("ECM organization", "Connected to COL1A1 hub; one of the strongest log2FC magnitudes among Up genes", "Literature search recommended (Step 9)"),
    "ZWINT":  ("Cell cycle / mitotic checkpoint", "PPI hub (degree 3); links proliferation theme (KEGG Cell cycle) to network", "Literature search recommended (Step 9)"),
}

biomarker_table["pathway"] = biomarker_table["gene_symbol"].map(lambda g: pathway_map[g][0])
biomarker_table["reason_selected"] = biomarker_table["gene_symbol"].map(lambda g: pathway_map[g][1])
biomarker_table["validation_evidence"] = biomarker_table["gene_symbol"].map(lambda g: pathway_map[g][2])

biomarker_table = biomarker_table.sort_values("FDR")
biomarker_table.to_csv("candidate_biomarker_table.csv", index=False)

print("Candidate biomarker table:", biomarker_table.shape[0], "genes")
biomarker_table
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (roc_auc_score, roc_curve, confusion_matrix,
                              classification_report, precision_score, recall_score, f1_score)
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

import os
project_path = "/content/drive/MyDrive/Lung_Cancer_Transcriptomics_Project"
os.chdir(project_path)

print("Now working in:", os.getcwd())
print("Files available:", sorted(os.listdir()))

from google.colab import drive
drive.mount('/content/drive')

import os
project_path = "/content/drive/MyDrive/Lung_Cancer_Transcriptomics_Project"
os.chdir(project_path)

print("Now working in:", os.getcwd())
print("Files available:", sorted(os.listdir()))
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (roc_auc_score, roc_curve, confusion_matrix,
                              classification_report, precision_score, recall_score, f1_score)
import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (roc_auc_score, roc_curve, confusion_matrix,
                              classification_report, precision_score, recall_score, f1_score)
import matplotlib.pyplot as plt
expr = pd.read_csv("GSE19804_expression_matrix.csv", index_col=0)
metadata = pd.read_csv("GSE19804_metadata.csv")
significant_deg_table_dedup = pd.read_csv("GSE19804_significant_DEG_table_genes.csv")
biomarker_table = pd.read_csv("candidate_biomarker_table.csv")

candidate_genes = biomarker_table["gene_symbol"].tolist()
print("Candidate biomarker genes for classifier:", candidate_genes)
full_deg_table = pd.read_csv("GSE19804_full_DEG_table_annotated.csv")
candidate_probes = full_deg_table[full_deg_table["gene_symbol"].isin(candidate_genes)][["probe_id", "gene_symbol"]].drop_duplicates(subset="gene_symbol")

X = expr.loc[candidate_probes["probe_id"]].T
X.columns = candidate_probes["gene_symbol"].values
X = X.merge(metadata[["sample_id", "condition", "pair_id"]], left_index=True, right_on="sample_id")

y = (X["condition"] == "Tumor").astype(int)
print("Feature matrix shape:", X.shape)
print(X[["sample_id", "condition", "pair_id"] + candidate_genes[:3]].head())
unique_patients = X["pair_id"].unique()
train_patients, test_patients = train_test_split(unique_patients, test_size=0.25, random_state=42)

train_mask = X["pair_id"].isin(train_patients)
test_mask = X["pair_id"].isin(test_patients)

X_train = X.loc[train_mask, candidate_genes]
X_test = X.loc[test_mask, candidate_genes]
y_train = y.loc[train_mask]
y_test = y.loc[test_mask]

print("Train patients:", len(train_patients), "-> samples:", X_train.shape[0])
print("Test patients:", len(test_patients), "-> samples:", X_test.shape[0])
print("Train class balance:\n", y_train.value_counts())
print("Test class balance:\n", y_test.value_counts())
overlap = set(train_patients) & set(test_patients)
print("Patient overlap between train/test (should be empty set):", overlap)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
clf = LogisticRegression(max_iter=1000, random_state=42)
clf.fit(X_train_scaled, y_train)

y_pred = clf.predict(X_test_scaled)
y_pred_proba = clf.predict_proba(X_test_scaled)[:, 1]
auc = roc_auc_score(y_test, y_pred_proba)
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = cm.ravel()

sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"ROC-AUC: {auc:.3f}")
print(f"Sensitivity (Recall, Tumor): {sensitivity:.3f}")
print(f"Specificity (Normal): {specificity:.3f}")
print(f"Precision: {precision:.3f}")
print(f"F1 Score: {f1:.3f}")
print("\nConfusion Matrix:")
print(f"                Predicted Normal  Predicted Tumor")
print(f"Actual Normal        {tn:^14} {fp:^14}")
print(f"Actual Tumor         {fn:^14} {tp:^14}")
fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba)

plt.figure(figsize=(7, 7))
plt.plot(fpr, tpr, color="#d62728", lw=2, label=f"ROC curve (AUC = {auc:.3f})")
plt.plot([0, 1], [0, 1], color="grey", lw=1, linestyle="--", label="Random classifier")
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Sensitivity)")
plt.title("ROC Curve: 9-Gene Biomarker Panel (Test Set)")
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("roc_curve.png", dpi=300)
plt.show()
from sklearn.model_selection import GroupKFold

groups_train = X.loc[train_mask, "pair_id"]
gkf = GroupKFold(n_splits=5)

cv_aucs = []
for fold, (tr_idx, val_idx) in enumerate(gkf.split(X_train, y_train, groups=groups_train)):
    X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]
    y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]

    fold_scaler = StandardScaler()
    X_tr_scaled = fold_scaler.fit_transform(X_tr)
    X_val_scaled = fold_scaler.transform(X_val)

    fold_clf = LogisticRegression(max_iter=1000, random_state=42)
    fold_clf.fit(X_tr_scaled, y_tr)
    fold_auc = roc_auc_score(y_val, fold_clf.predict_proba(X_val_scaled)[:, 1])
    cv_aucs.append(fold_auc)
    print(f"Fold {fold+1} AUC: {fold_auc:.3f}")

print(f"\nMean CV AUC: {np.mean(cv_aucs):.3f} (+/- {np.std(cv_aucs):.3f})")
results_summary = pd.DataFrame({
    "metric": ["Test AUC", "Sensitivity", "Specificity", "Precision", "F1", "Mean CV AUC", "CV AUC Std"],
    "value": [auc, sensitivity, specificity, precision, f1, np.mean(cv_aucs), np.std(cv_aucs)]
})
results_summary.to_csv("classifier_performance_summary.csv", index=False)
print(results_summary)