utils::globalVariables(
  c(
    "ENSEMBL",
    "ENTREZID",
    "FEATURE",
    "SYMBOL",
    "padj",
    "log2FoldChange",
    "negLog10Padj",
    "significance",
    "condition",
    "PC1",
    "PC2",
    "baseMean",
    "lfcSE",
    "stat",
    "pvalue",
    "ensembl_gene_id",
    "external_gene_name",
    ".data",
    "library_size",
    "detected_genes",
    "n_flags",
    "qc_status",
    "score",
    "marker_set"
  )
)
