#' Generate DEGgo HTML/PDF Report
#'
#' Creates a DEGgo analysis report from the results generated by `run_deggo()`.
#'
#' @param results DEGgo results object returned by `run_deggo()`.
#' @param output_dir Output directory.
#' @param formats Character vector. Supported values: `"html"` and `"pdf"`.
#' @param report_template Optional path to custom R Markdown template.
#'
#' @return Invisibly returns generated report paths.
#' @export
generate_deggo_report <- function(
    results,
    output_dir = results$output_dir,
    formats = "html",
    report_template = NULL
) {

  `%||%` <- function(x, y) if (is.null(x)) y else x

  if (!requireNamespace("rmarkdown", quietly = TRUE)) {
    stop("Package 'rmarkdown' is required.", call. = FALSE)
  }

  if (is.null(report_template)) {
    report_template <- system.file(
      "rmarkdown/templates/deggo_report/skeleton/skeleton.Rmd",
      package = "DEGgo"
    )
  }

  if (!nzchar(report_template) || !file.exists(report_template)) {
    stop("Report template not found: ", report_template, call. = FALSE)
  }

  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  out_files <- character()

  for (fmt in formats) {

    output_file <- if (fmt == "html") {
      "DEGgo_Report.html"
    } else {
      "DEGgo_Report.pdf"
    }

    rendered <- NULL

    rendered <- tryCatch(
      rmarkdown::render(
        input = report_template,
        output_file = output_file,
        output_dir = output_dir,
        params = list(
          results = results,
          sig_deg = results$sig_deg,
          go_results = results$go_results,
          summary = results$summary,
          metadata = results$metadata,
          output_dir = output_dir
        ),
        envir = new.env(parent = globalenv()),
        quiet = TRUE
      ),
      error = function(e) {
        warning("Report generation failed: ", conditionMessage(e), call. = FALSE)
        NULL
      }
    )

    if (!is.null(rendered)) {
      report_files[[fmt]] <- rendered
    }

    out_files <- c(out_files, rendered)
  }

  cat("[INFO] DEGgo report generation completed.")

  invisible(out_files)
}
