#' Generate DEGgo HTML/PDF Report
#'
#' Creates a comprehensive DEGgo analysis report from the results
#' generated by \code{run_deggo()}. The report summarizes differential
#' expression results, enriched Gene Ontology terms, quality control
#' metrics, and associated visualizations.
#'
#' Reports can be generated in HTML and/or PDF format using an
#' R Markdown template.
#'
#' @param results A DEGgo results object returned by
#'   \code{\link{run_deggo}}.
#' @param output_dir Character. Directory where report files will be
#'   written. Defaults to \code{results$output_dir}.
#' @param formats Character vector specifying report format(s).
#'   Supported values are \code{"html"} and \code{"pdf"}.
#' @param report_template Optional path to an R Markdown template.
#'   If \code{NULL}, DEGgo attempts to locate a bundled template
#'   automatically.
#' @param quiet Logical. If TRUE, suppress rendering messages.
#'
#' @importFrom rmarkdown render
#' @importFrom rmarkdown html_document
#' @importFrom rmarkdown pdf_document
#'
#' @details
#' The report includes:
#'
#' \itemize{
#'   \item Analysis summary
#'   \item Differentially expressed genes
#'   \item Volcano plots
#'   \item PCA visualizations
#'   \item Heatmaps
#'   \item Gene Ontology enrichment results
#'   \item Session information
#' }
#'
#' PDF report generation requires a LaTeX installation
#' (e.g. TinyTeX).
#'
#' @return
#' A named list containing paths to generated report files.
#' Invisibly returned.
#'
#' @seealso \code{\link{run_deggo}}, \code{\link{run_go_enrichment}},
#'   \code{export_deg_results()}
#'
#' @examples
#' \dontrun{
#'
#' report_files <- generate_deggo_report(
#'   results = deggo_results,
#'   formats = c("html", "pdf")
#' )
#'
#' report_files$html
#' report_files$pdf
#'
#' }
#'
#' @export
#'
generate_deggo_report <- function(
    results,
    output_dir = results$output_dir,
    formats = c("html", "pdf"),
    quiet = TRUE,
    report_template = NULL
) {

  log <- .msg(verbose = TRUE)

  formats <- match.arg(
    formats,
    choices = c("html", "pdf"),
    several.ok = TRUE
  )

  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

  if (is.null(report_template)) {

    candidates <- c(
      file.path(getwd(), "skeleton.Rmd"),
      file.path(output_dir, "skeleton.Rmd"),
      system.file(
        "rmarkdown/templates/deggo_report/skeleton/skeleton.Rmd",
        package = "DEGgo"
      )
    )

    candidates <- candidates[nzchar(candidates)]

    report_template <- candidates[file.exists(candidates)][1]
  }

  message("report_template = ", report_template)
  message("template_exists = ", file.exists(report_template))

  if (length(report_template) == 0 ||
      is.na(report_template) ||
      !file.exists(report_template)) {

    log("skeleton.Rmd not found. Skipping report.", type = "warn")
    return(NULL)
  }

  report_template <- normalizePath(
    report_template,
    winslash = "/",
    mustWork = TRUE
  )

  report_files <- list()

  for (fmt in formats) {

    log(paste("Generating", toupper(fmt), "report..."))

    output_format <- switch(
      fmt,
      html = rmarkdown::html_document(
        toc = TRUE,
        toc_depth = 3,
        theme = "flatly",
        self_contained = TRUE
      ),
      pdf = rmarkdown::pdf_document(
        toc = TRUE,
        toc_depth = 3,
        number_sections = TRUE
      )
    )

    output_file <- paste0("DEGgo_Report.", fmt)

    report_files[[fmt]] <- tryCatch(
      rmarkdown::render(
        input = report_template,
        output_file = output_file,
        output_dir = output_dir,
        output_format = output_format,
        params = list(
          results = results,
          sig_deg = results$sig_deg,
          go_results = results$go_results,
          summary = results$summary,
          output_dir = output_dir
        ),
        envir = new.env(parent = globalenv()),
        quiet = FALSE
      ),
      error = function(e) {
        log(
          paste("Failed to generate", fmt, "report:", e$message),
          type = "warn"
        )
        NULL
      }
    )
  }

  report_files
}
