#' Generate DEGgo HTML/PDF Report
#'
#' Creates a comprehensive DEGgo analysis report from the results
#' generated by \code{run_deggo()}.
#'
#' @param results A DEGgo results object returned by \code{run_deggo()}.
#' @param output_dir Character. Output directory.
#' @param formats Character vector. Supported values: \code{"html"}, \code{"pdf"}.
#' @param quiet Logical. Suppress rendering messages.
#' @param report_template Optional path to custom R Markdown template.
#'
#' @return
#' Invisibly returns a named list containing generated report paths.
#'
#' @export
generate_deggo_report <- function(
    results,
    output_dir = results$output_dir,
    formats = c("html", "pdf"),
    quiet = FALSE,
    report_template = NULL
) {


  log <- .msg(verbose = !quiet)

  formats <- match.arg(
    formats,
    choices = c("html", "pdf"),
    several.ok = TRUE
  )

  dir.create(
    output_dir,
    recursive = TRUE,
    showWarnings = FALSE
  )

  # ------------------------------------------------------
  # Locate RMarkdown template
  # ------------------------------------------------------

  if (is.null(report_template)) {

    candidates <- c(
      # Installed package
      system.file(
        "rmarkdown/templates/deggo_report/skeleton/skeleton.Rmd",
        package = "DEGgo"
      ),

      # Development source tree
      file.path(
        getwd(),
        "inst/rmarkdown/templates/deggo_report/skeleton/skeleton.Rmd"
      ),

      # Relative to project
      file.path(
        dirname(output_dir),
        "inst/rmarkdown/templates/deggo_report/skeleton/skeleton.Rmd"
      ),

      # Local fallback
      file.path( getwd(), "skeleton.Rmd"))

    candidates <- candidates[
      nzchar(candidates) &
        file.exists(candidates)
    ]

    if (length(candidates) > 0) {
      report_template <- candidates[1]
    } else {
      report_template <- NULL
    }
  }

  log( paste0("report_template = ",
      ifelse(is.null(report_template),
        "NULL", report_template)
      )
      )

  if (
    is.null(report_template) ||
    !file.exists(report_template)
  ) {

    log("skeleton.Rmd not found. Skipping report.", type = "warn")

    return(invisible(NULL))
  }

  report_template <- normalizePath(
    report_template,
    winslash = "/",
    mustWork = TRUE
  )

  report_files <- list()



  # ------------------------------------------------------
  # Render reports
  # ------------------------------------------------------

  for (fmt in formats) {
    log(paste("Generating", toupper(fmt), "report..."))

    output_format <- switch(
      fmt,
      html = rmarkdown::html_document(
        toc = TRUE,
        toc_depth = 3,
        theme = "flatly",
        self_contained = TRUE
      ),
      pdf = rmarkdown::pdf_document(
        toc = TRUE,
        toc_depth = 3,
        number_sections = TRUE
      )
    )

    output_file <- paste0("DEGgo_Report.", fmt)

    report_files[[fmt]] <- rmarkdown::render(
      input = report_template,
      output_file = output_file,
      output_dir = output_dir,
      output_format = output_format,
      params = list(
        results = results,
        sig_deg = results$sig_deg,
        go_results = results$go_results,
        summary = results$summary,
        metadata = results$metadata %||% NULL,
        output_dir = output_dir
      ),
      envir = new.env(parent = globalenv()),
      quiet = quiet
    )
  }

  log(paste("report_template =", report_template))

  log("DEGgo report generation completed.")

  invisible(report_files)

}
